### ISSUE TITLE
/games returns 502

### ISSUE THREAD

**Issue by wight-airmash** [airmash-refugees/airmash-services#1]
Currently `https://data.airmash.online/games` response:

```http
HTTP/1.1 502 Bad Gateway
Connection: keep-alive
Content-Length: 166
Content-Type: text/html; charset=utf-8
Date: Sat, 28 Dec 2019 11:01:38 GMT
Server: nginx

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by congratulatio** [comment]
Thanks for reporting. The VM hosting these services rebooted unexpectedly and when it came back up, some of the services, including `/games`, didn't start up as expected. I'm still investigating why this happened, but everything should be back to normal now.
