### ISSUE TITLE
"data.airmash.online" and "login.airmash.online" connection timed out

### ISSUE THREAD

**Issue by wight-airmash** [airmash-refugees/airmash-services#6]
@congratulatio 

![cto](https://user-images.githubusercontent.com/38955076/200190017-16df9e1f-c7f6-4e01-b67f-34faee5ed781.png)

**Comment by congratulatio** [comment]
Turns out that the server got automatically disabled by the hosting provider, because of an expired payment method that I hadn't noticed in time. Fixed now, sorry for the outage.
